sudo: true
language: haskell

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work"

matrix:

  include:

  - ghc: 8.2.2
    env: STACK_YAML="$HOME/build/serokell/serokell-util/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.0.2
    env: STACK_YAML="$HOME/build/serokell/serokell-util/stack-8.0.2.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.2.2
    env: GHCVER='8.2.2' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.2.2
        - cabal-install-head

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      cabal new-update
      cabal new-build serokell-util --only-dependencies
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal --upgrade-cabal
      stack ghc -- --version
      stack build --only-dependencies --no-terminal
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test all
    else
      stack build --test --bench --no-terminal
    fi

notifications:
  email: false
  slack:
    rooms:
      - serokell:uMIv04MagaYHz0jlBa9jaiVy
    on_success: change
    on_failure: always
